export const SET_PRODUCTS="SET_PRODUCTS";
export const SELECTED_PRODUCTS="SELECTED_PRODUCTS";
export const ITEM_ADDED ="ITEM_ADDED";
export const ITEM_REMOVED="ITEM_REMOVED";
export const CART_ITEM_ADDED = "CART_ITEM_ADDED";
export const QTY_ADDED='QTY_ADDED';
